// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license.

// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Bot.Connector.DirectLine
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// An object representing a conversation or a conversation token
    /// </summary>
    public partial class Conversation
    {
        /// <summary>
        /// Initializes a new instance of the Conversation class.
        /// </summary>
        public Conversation() { }

        /// <summary>
        /// Initializes a new instance of the Conversation class.
        /// </summary>
        public Conversation(string conversationId = default(string), string token = default(string), int? expiresIn = default(int?), string streamUrl = default(string), string referenceGrammarId = default(string), string eTag = default(string))
        {
            ConversationId = conversationId;
            Token = token;
            ExpiresIn = expiresIn;
            StreamUrl = streamUrl;
            ReferenceGrammarId = referenceGrammarId;
            ETag = eTag;
        }

        /// <summary>
        /// ID for this conversation
        /// </summary>
        [JsonProperty(PropertyName = "conversationId")]
        public string ConversationId { get; set; }

        /// <summary>
        /// Token scoped to this conversation
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// Expiration for token
        /// </summary>
        [JsonProperty(PropertyName = "expires_in")]
        public int? ExpiresIn { get; set; }

        /// <summary>
        /// URL for this conversation's message stream
        /// </summary>
        [JsonProperty(PropertyName = "streamUrl")]
        public string StreamUrl { get; set; }

        /// <summary>
        /// ID for the reference grammar for this bot
        /// </summary>
        [JsonProperty(PropertyName = "referenceGrammarId")]
        public string ReferenceGrammarId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eTag")]
        public string ETag { get; set; }

    }
}
