// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Bot.Connector.DirectLine
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Thing (entity type: "https://schema.org/Thing")
    /// </summary>
    public partial class Thing
    {
        /// <summary>
        /// Initializes a new instance of the Thing class.
        /// </summary>
        public Thing() { }

        /// <summary>
        /// Initializes a new instance of the Thing class.
        /// </summary>
        public Thing(string type = default(string), string name = default(string))
        {
            Type = type;
            Name = name;
        }

        /// <summary>
        /// The type of the thing
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// The name of the thing
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
